### ISSUE TITLE
Message From Jake

### ISSUE THREAD

**Issue by IAmJSD** [AuroraCommunity/AuroraWebsite#103]
I joined here early this year. I was just demoted in another server for being a mild physcopath, was going through a LOT of mental health issues and was ill almost daily from school. I became friends with REC. I related to him because of the area of the country we both lived in.

I talked in Aurora for a while. I learned who a lot of the members were and generally relaxed a lot more in that server than others. I met REC. I remember being in a voice call with him and my IRL friend in KFC lol. I made it to Mod and was demoted due to beef. Even when I hated Da532 and his friends, I was still able to stay in Aurora.

I got given Administrator. It felt like I had power on a massive server. I feel I was very responsible that time with it. Then the first server nuke happened and I got demoted.

After that, I applied for Mod and got accepted. I feel I did a pretty good job. It was removed during the second nuke and never added because they felt like they had enough moderation.

Thats my history. It has helped me because it made me feel like I was a part of something during my lowest times.

Rest in peace Aurora,
Jake

**Comment by t5r7** [comment]
Added in #108
