### ISSUE TITLE
Message From oskikiboy - Oscar

### ISSUE THREAD

**Issue by oskikiboy** [AuroraCommunity/AuroraWebsite#109]
Aurora ment many things to me, it was a place to chat, a place to make friends, and a place to make China memes. I'll miss you Aurora!

**Comment by oskikiboy** [comment]
ayy

**Comment by oskikiboy** [comment]
Nothing happened

**Comment by oskikiboy** [comment]
Ill do it myself

**Comment by oskikiboy** [comment]
Some day

**Comment by t5r7** [comment]
oi @aerofusionyt why aren't you adding any of these

**Comment by ghost** [comment]
tom i thought you were supposed to add these
i break things

**Comment by t5r7** [comment]
Added in https://github.com/AuroraCommunity/AuroraWebsite/commit/44973e2d725b65cdfd110ce7158639acc4b4f649
Blame Espi for it taking so long.
