### ISSUE TITLE
Message From Lazer

### ISSUE THREAD

**Issue by laz3rpenguin** [AuroraCommunity/AuroraWebsite#110]
Aurora was the first massive server I ever joined and right from the get-go, it pretty much changed my life. I remember getting the Trusted role and it was definitely one of the best days of my life. I joined Armada back when it was first created and I began my conquest to become staff on a major server. Soon after that, I was made staff on Armada and the demoted. Then both Armada and Aurora got nuked :(. Skip forward a few months and things have changed a lot. I was made Moderator on Armada and soon after that, we merged with WindowsWorld to create Novus. Hearing that Aurora was being shut down was some really sad news. 

Thanks to everyone who made my time at Aurora awesome ;)

~ Lazer

**Comment by t5r7** [comment]
Added the version you submitted to the GForm in #111. @aerofusionyt's doing the quotes from now on, you'll have to ask him if you want this version.

**Comment by t5r7** [comment]
Dammit @aerofusionyt don't close issues until you've actually added the comment you tool

**Comment by t5r7** [comment]
Added in https://github.com/AuroraCommunity/AuroraWebsite/commit/44973e2d725b65cdfd110ce7158639acc4b4f649
Blame Espi for it taking so long.
