### ISSUE TITLE
Message From Billy (Nerdkilervip)

### ISSUE THREAD

**Issue by billyprice1old** [AuroraCommunity/AuroraWebsite#115]
Aurora Community was my life i was a big meme for all the  even tho aurora  have had a rough history i stood by it even after the nuke i was a Mod in aurora for a short time that was my best time in the community all the drama the Gorden rasmy memes and memes about my English and  me talking about my servers i loved it then Novus came along and That is where i spend most of my time now 
~ Billy

**Comment by ghost** [comment]
fix your grammar and then ill add it
also comment for yourself not "ibilly media group"
thx

**Comment by billyprice1old** [comment]
Fixed

**Comment by ghost** [comment]
i fixed some more grammar and posted it
