### ISSUE TITLE
Add button that links to Novus

### ISSUE THREAD

**Issue by vladfrangu** [AuroraCommunity/AuroraWebsite#116]
@mrdnomaid @aerofusionyt should we add another button on the site (other side of the join netsky community) to Novus? I know some may dislike it, but it may be a good idea.

**Comment by t5r7** [comment]
I mean I'm not against it, I just don't think there's room for 3 buttons, at least without it looking terrible.

**Comment by t5r7** [comment]
Plus, NC is the """actual""" successor to Aurora

**Comment by ghost** [comment]
yeah it would look pretty bad
