### ISSUE TITLE
Message From akuma67

### ISSUE THREAD

**Issue by akuma67** [AuroraCommunity/AuroraWebsite#117]
To be honest, Aurora was my favourite discord server.  Sure, I did get my fair share of strikes, but it was fun.  I'm really sad to see it go, but hopefully we can go on.

-akuma67

**Comment by ghost** [comment]
will add later, on mobile. @mrdnomaid

**Comment by ghost** [comment]
I have completed this and added a pull request.

**Comment by ByteOfMelon** [comment]
@aerofusionyt you do realise you can close this now right

**Comment by akuma67** [comment]
I was never added to the site @TheRandomMelon

**Comment by ByteOfMelon** [comment]
@akuma67 I thought you were...?

**Comment by akuma67** [comment]
Nah, I wasn't.  Even though it's on the site code, it's not on the site itself

**Comment by akuma67** [comment]
Wait nevermind, its just CloudFlare being retarded
