### ISSUE TITLE
Extension of my message

### ISSUE THREAD

**Issue by DanJBee** [AuroraCommunity/AuroraWebsite#98]
If you could extend my message to this it would be appreciated:

Well, this is awkard isn't it...

I joined Aurora in like summer of 2017, and I gained popularity very quickly, and I really enjoyed it here.. 
Then, within 3 weeks I was a Manager, a shocking thing which I didn't expect to happen. Soon after I got Manager, devon went on a crazy one and started doing shit here an there, and stuff was happening.
After this event, devon asked me to destroy the server.. but my morals stopped me.. but then he brought up the idea of doing it with my bot.. but usng my token.. this caused alot of shit and all that began from there was a shitheap, to be fair, I actually regretted it at some points, remembering the fun times, wether it me being mocked by people for my crap music, or me making unfunny Gordon Ramsay memes, they were fun, I'll never forget those moments. 

I guess I'm just sorry for finally admitting to this at this time, but I hope it just goes upwards from here I guess, and I wish you the best of luck in doing so. I'm banned from NC I'm afraid, due to Espi banning me for whatever reason, and I'm a sensible human who won't be able to stay up until 1am to watch the death of Aurora once and for all. But, apart from that, cya I guess.

- Dan, the best chef.

**Comment by t5r7** [comment]
Fixed in #102
