### ISSUE TITLE
Message From theLMGN

### ISSUE THREAD

**Issue by foxt** [AuroraCommunity/AuroraWebsite#99]
I was one of the first members to join the server when it became public, and was in the server before Novus, before Aurora, before WindowsWorld, Before REG+Friends, back when it was ScamCentral. I helped make the original AuroraBot and AuroraRadio, and even hosted it for a while if memory serves correct. I've seen members come and go. Staff members come and go. Memes come and go. The server being nuked. Talking in #mainchat in my downtime at school. Partnership come and go. Reputation come and go. **Memories come and stay.**

I loved it. I'm sad to see Aurora go.
I like to think I tried my best when it came to Aurora.
-- Thanks for reading. Thanks for being a part of this great community.
    Leo (theLMGN)

**Comment by t5r7** [comment]
Added in #102
